Configure max profiles to merge instead use max size
apache/unomi pull request #247
Opened 2021-02-08 06:59 UTC by liatiusim

Added the ability to configure max profiles to merge in a merge action (instead using "-1" hard coded), due to performance issues - when the size is "-1" , the `query()` call generates additional 2 calls - scroll query and the deletion of the scroll.
This is not needed when we know there is a few profiles to merge.

note - since the baseplugin has no cgf file, I wasn't sure what should be done in order to expose it to environment variable (currently it is configurable only from the blueprint file). Would be glad to get your advise about that. Thanks

2021-02-10 12:21 UTC, sergehuber requested changes
Hello Liat, thanks for the PR, but it doesn't seem complete, I don't see where the new variable is being used?

2021-02-12 13:22 UTC, sergehuber commented
To address the question of where to put the configuration, a new configuration file for the base plugin could be added, something like org.apache.unomi.plugins.base.cfg. See the other bundles for examples on how to set that up.

2021-03-10 14:55 UTC, sergehuber commented
Hi @liatiusim any updates on this PR?

2021-04-04 13:59 UTC, liatiusim commented
Hey Serge,
Added the Jira number and added a cfg file
Thanks for the review

2021-04-16 15:00 UTC, sergehuber approved these changes
Thanks Liat for providing all the files. Looks good to me.

2021-04-19 08:19 UTC, merged