UNOMI-492 Make rules engine more robust when some rules are invalid (null actions)
apache/unomi pull request #314
Opened 2021-06-24 16:42 UTC by sergehuber

Here's what was achieved in this PR: 
- Make sure we handle null actions gracefully instead of generating a NPE and blocking loading of further rules
- Add an integration test to test the case of null actions in rule
- Improve logging when rules have null or empty conditions and actions

2021-06-25 07:02 UTC, jkevan requested changes

2021-06-25 09:21 UTC, sergehuber commented on itests/src/test/java/org/apache/unomi/itests/RuleServiceIT.java
> +        assertEquals("Rule not properly saved", initialRuleCount + 1, lastRuleCount);
yes you are right I need to correct that. Thanks for catching it.

2021-06-25 13:31 UTC, sergehuber commented on itests/src/test/java/org/apache/unomi/itests/RuleServiceIT.java
> +        assertEquals("Rule not properly saved", initialRuleCount + 1, lastRuleCount);
Ok I've modified the test to simply use getRule

2021-06-28 08:19 UTC, jkevan approved these changes

2021-06-28 11:04 UTC, merged